### ISSUE TITLE
Could you please share your paper?

### ISSUE THREAD

**Issue by wypppp** [confiwent/BayesMPC#1]
Hello，
I am interested in your paper, so could you please share your paper?
Thanks！

**Comment by confiwent** [comment]
Hi, thanks for your interests! Our paper has been accepted by NOSSDAV 2021, and will be published online within a few months.

Attached is the accepted paper. Please let me know if you have any questions about the paper.


Best regards,


阚诺文
Nuowen Kan
--------------------------
Ph.D student
Institute of Media, Information, and Network （M.I.N）
Department of Electronic Engineering
Shanghai Jiao Tong University, Shanghai, 200240, China
SEIEE Building 1-307
Phone: +86 18516418125



From: wypppp ***@***.***>
Sent: Friday, May 21, 2021 9:28 PM
To: confiwent/BayesMPC ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [confiwent/BayesMPC] Could you please share your paper? (#1)


Hello，
I am interested in your paper, so could you please share your paper?
Thanks！

―

**Comment by wypppp** [comment]
> Hi, thanks for your interests! Our paper has been accepted by NOSSDAV 2021, and will be published online within a few months. Attached is the accepted paper. Please let me know if you have any questions about the paper. Best regards, 阚诺文 Nuowen Kan -------------------------- Ph.D student Institute of Media, Information, and Network （M.I.N） Department of Electronic Engineering Shanghai Jiao Tong University, Shanghai, 200240, China SEIEE Building 1-307 Phone: +86 18516418125 From: wypppp ***@***.***> Sent: Friday, May 21, 2021 9:28 PM To: confiwent/BayesMPC ***@***.***> Cc: Subscribed ***@***.***> Subject: [confiwent/BayesMPC] Could you please share your paper? (#1) Hello， I am interested in your paper, so could you please share your paper? Thanks！ ― You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconfiwent%2FBayesMPC%2Fissues%2F1&data=04%7C01%7C%7C103df1a4ec2e4bfd91fc08d91c5c4128%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637572004815538632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oAlwvO%2FrEoOfiawRe7lNzTq1E%2BquRWWHIlB6BMEsPuQ%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHLOQBCGJLBWVK62MOQLR5LTOZNWBANCNFSM45JE6ASQ&data=04%7C01%7C%7C103df1a4ec2e4bfd91fc08d91c5c4128%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637572004815548591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6QpKxPgTpx9LbOrpNplgxWU4q1v3us0pJ7lSyZYULaA%3D&reserved=0>.


I am replicating your experiment and I would like to know how you predict throughput. After puffer, I don't think throughput is a very important metric, so I'm wondering if you have an innovative design.
Also, if I want to use VMAF as a QoE evaluation metric, how should I add it in?
Thanks！
